### ISSUE TITLE
`dfget --limit` doesn't work

### ISSUE THREAD

**Issue by ismewen** [dragonflyoss/Dragonfly2#1377]
### Bug report:

`dfget --limit` doesn't work， the download speed does not follow the specified speed。
### Expected behavior:

The download speed follow the specified speed

### How to reproduce it:

./dfget --limit 1G -u http://10.190.113.78:8001/1gfile.tgz -b
 ./dfget --limit 10M -u http://10.190.113.78:8001/1gfile.tgz -b
<img width="471" alt="image" src="https://user-images.githubusercontent.com/30500262/173348830-52ddbbcf-606b-4e6f-9fa4-347f678e3327.png">

### Environment:
- Dragonfly version: 2.0.3
- OS: centos
- Kernel (e.g. `uname -a`):  SMP Wed Sep 29 11:01:45 CST 2021 x86_64 x86_64 x86_64 GNU/Linux
- Others:

**Comment by 1037husterljx** [comment]
- The command line flag limit should be ratelimit
- ratelimit deserialization failed, change type to solve
- When ratelimit limit is too low, below the download size of the slice, otherwise it will fail back to the source
- The ratelimit rate described by -b is limited and cannot describe the speed limit of p2p network

**Comment by gaius-qi** [comment]
> * The command line flag limit should be ratelimit
> * ratelimit deserialization failed, change type to solve
> * When ratelimit limit is too low, below the download size of the slice, otherwise it will fail back to the source
> * The ratelimit rate described by -b is limited and cannot describe the speed limit of p2p network

Thx 🐂🐂🐂
