### ISSUE TITLE
dfget tools resolv hostname but not exist how to not do it

### ISSUE THREAD

**Issue by 395096713** [dragonflyoss/Dragonfly2#2305]
### Bug report:

when i use dfget tools on my device , i found it try resolv hostname  dns domain,but the hostname we don not config  dns ip ,many devices generate many invalid DNS requests

### Expected behavior:

1、why dfget tools try to resolv hostname of the device ？
2、if can support parameter to control this behavior，do not resolv hostname because it not exists

### How to reproduce it:

dfget download url,and tcpdump -i any udp and port 53 ,can see try to resolv hostname  domain ip

### Environment:

- Dragonfly version:dragonfly2
- OS:centos
- Kernel (e.g. `uname -a`):3.10.0-693.el7.x86_64
- Others:

**Comment by gaius-qi** [comment]
dfget needs to take the hostname and ip of the machine to generate a unique id. Please check why your environment does not support hostname resolution. The library used by dragonfly to resolve hostname is https://github.com/Showmax/go-fqdn.

I think the problem is with your local environment, not with dragonfly.
