### ISSUE TITLE
Questions: wonder what seedpeer does

### ISSUE THREAD

**Issue by cheriL** [dragonflyoss/Dragonfly2#2495]
Hi Community:
  I have read the official docs and the scheduler/dfdaemon configurations. I have a little confused about peers and seedpeers. A few questions:
1. If I do not need image preheat, and set `scheduler.seedPeer.enable=false`, Do I still need to deploy seedpeer statefulset?
2. Regardless of preheat, what else does seedpeer do?
3. How is the port 65001 of the peer exposed that I do not see `hostNetwork: true` or `NodePort`?

**Comment by jim3ma** [comment]
Seed Peer is similar with a normal peer. The most different is Scheduler will let Seed Peer to download from source preferentially, because normal we deploy Seed Peer with more powerful spec, eg: high CPU and memory, large disk.

1. If I do not need image preheat, and set scheduler.seedPeer.enable=false, Do I still need to deploy seedpeer statefulset?
You did not need to deploy it.

2. Regardless of preheat, what else does seedpeer do?
Same with previous description.

3. How is the port 65001 of the peer exposed that I do not see hostNetwork: true or NodePort?
Can you give some example config or spec ?

**Comment by jim3ma** [comment]
Seed Peer is similar with a normal peer. The most different is Scheduler will let Seed Peer to download from source preferentially, because normal we deploy Seed Peer with more powerful spec, eg: high CPU and memory, large disk.

1. If I do not need image preheat, and set scheduler.seedPeer.enable=false, Do I still need to deploy seedpeer statefulset?
You did not need to deploy it.

2. Regardless of preheat, what else does seedpeer do?
Same with previous description.

3. How is the port 65001 of the peer exposed that I do not see hostNetwork: true or NodePort?
Can you give some example config or spec ?

**Comment by cheriL** [comment]
@jim3ma Thanks for your quick reply! 
I deployed dragonfly on k8s(v1.24, runtime: containerd 1.6) via helm following the quickstart [guide](https://d7y.io/docs/getting-started/quick-start/kubernetes/#create-dragonfly-cluster-based-on-helm-charts). 
How does containerd send requests to dfdaemon through 127.0.0.1:65001?

**Comment by gaius-qi** [comment]
> @jim3ma Thanks for your quick reply! I deployed dragonfly on k8s(v1.24, runtime: containerd 1.6) via helm following the quickstart [guide](https://d7y.io/docs/getting-started/quick-start/kubernetes/#create-dragonfly-cluster-based-on-helm-charts). How does containerd send requests to dfdaemon through 127.0.0.1:65001?

@cheriL Yes
