### ISSUE TITLE
downgrade gorm.io/driver/postgres to 1.5.2

### ISSUE THREAD

**Issue by pbannykh** [dragonflyoss/Dragonfly2#2907]
### Bug report:

Updating gorm.io/driver/postgres from 1.5.2 to 1.5.3, as well as 1.5.4, broke registration of schedulers.
Log: table name "scheduler" specified more than once.

### Expected behavior:

downgrade gorm.io/driver/postgres to 1.5.2

### How to reproduce it:

Use postgresql, add more than one scheduler

### Environment:

- Dragonfly version: 2.1.17 - 2.1.23
- OS: linux
- Kernel (e.g. `uname -a`): 6.1.27-1
- Others: kubernetes

**Comment by PKizzle** [comment]
Is this a bug introduced at gorm.io/driver/postgres with version 1.5.3 or are code changes required in the Dragonfly2 project?

**Comment by gaius-qi** [comment]
> Is this a bug introduced at gorm.io/driver/postgres with version 1.5.3 or are code changes required in the Dragonfly2 project?

@pbannykh

**Comment by PKizzle** [comment]
@gaius-qi Since there seem to be other issues with gorm.io/driver/postgres versions 1.5.3 and newer would it be possible to downgrade it to 1.5.2 until fixed?
For example: https://github.com/go-gorm/postgres/issues/225

I can not tell whether this specific issue of a table name being specified more than once is something that needs to be fixed in this project or in the gorm postgres driver. However, all releases of Dragonfly since 2.1.16 contain a non functioning driver version and are broken for postgres users. For the time being I highly suggest to downgrade the dependency should there not be another reason for keeping the newer version.

**Comment by gaius-qi** [comment]
> @gaius-qi Since there seem to be other issues with gorm.io/driver/postgres versions 1.5.3 and newer would it be possible to downgrade it to 1.5.2 until fixed? For example: [go-gorm/postgres#225](https://github.com/go-gorm/postgres/issues/225)
> 
> I can not tell whether this specific issue of a table name being specified more than once is something that needs to be fixed in this project or in the gorm postgres driver. However, all releases of Dragonfly since 2.1.16 contain a non functioning driver version and are broken for postgres users. For the time being I highly recommend to downgrade the dependency should there not be another reason for keeping the newer version.

@PKizzle Thanks!

**Comment by gaius-qi** [comment]
@pbannykh @PKizzle I have released new version [v2.1.25](https://github.com/dragonflyoss/Dragonfly2/tree/v2.1.25).
